stages:
  - build
  - deploy

image: node:20

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - GITLAB_PAGES=1 npm run build
  artifacts:
    paths:
      - dist
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
